alias hs="history | grep"
alias myip="curl http://ipecho.net/plain; echo"
alias sandbox="code $HOME/dev/sandbox"
alias dotfiles="/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME"
alias rm="rm -i"
