[cursor.style]
shape = "Beam"

[font.bold]
family = "Fira Code"
style = "Bold"

[font.normal]
family = "Fira Code"
style = "Regular"

[[keyboard.bindings]]
chars = "\u001B[13;5u"
key = "Return"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[13;2u"
key = "Return"
mods = "Shift"

[shell]
args = ["--login"]
program = "/bin/zsh"

[window]
opacity = 0.75

[window.padding]
x = 15
y = 15
